services:
  backend:
    build: .
    container_name: ulechu_backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=uu_user
      - POSTGRES_PASSWORD=uu_passwd
      - POSTGRES_DB=uu_db
      - POSTGRES_SERVER=db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:15-alpine
    container_name: ulechu_db
    restart: always
    environment:
      - POSTGRES_USER=uu_user
      - POSTGRES_PASSWORD=uu_passwd
      - POSTGRES_DB=uu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
